fun main() {
    println("Advent Of Code 2023!")
//    println("-------Day 1-------")
//    println("part1: ${day1.part1()}")
//    println("part2: ${day1.part2()}")
//    println("-------------------")
//    println("-------Day 2-------")
//    println("part1: ${day2.part1()}")
//    println("part2: ${day2.part2()}")
//    println("-------------------")
//    println("-------Day 3-------")
//    println("part1: ${day3.part1()}")
//    println("part2: ${day3.part2()}")
//    println("-------------------")
//    println("-------Day 4-------")
//    println("part1: ${day4.part1()}")
//    println("part2: ${day4.part2()}")
//    println("-------------------")
    println("-------Day 5-------")
    println("part1: ${day5.part1()}")
    println("part2: ${day5.part2()}")
    println("-------------------")
}